### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by kovnew** [scir-zywang/self-training-self-supervised-disfluency#3]
程序运行似乎缺少一些文件，导致无法运行成功
```
Traceback (most recent call last):
  File "run_disfluency_finetune_eval_each_electra_st.py", line 1914, in <module>
    main()
  File "run_disfluency_finetune_eval_each_electra_st.py", line 802, in main
    state = torch.load(new_model_file)
  File "/home/hadoop-speech/.conda/envs/ss_disfluency/lib/python3.7/site-packages/torch/serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/hadoop-speech/.conda/envs/ss_disfluency/lib/python3.7/site-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/hadoop-speech/.conda/envs/ss_disfluency/lib/python3.7/site-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'run_model/3000/pytorch_model.bin'
mv: cannot stat ‘run_data/4000/unlabel_results.txt’: No such file or directory
```

**Comment by scir-zywang** [comment]
这里报错是因为缺少了完整SWBD数据集，模型没能拟合，导致后续出错。只要将完整的SWBD数据集放到data/500文件夹下即可。
